name: Validate Composer Config
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - name: Validate Composer Config
      uses: php-actions/composer@v6
      with:
        command: validate
        only_args: --strict
